export const ActionTypes = {
    SET_PRODUCTS : 'SET_PRODUCTS',
    SET_SELECTED_PRODUCTS : 'SET_SELECTED_PRODUCTS',
    REMOVE_SELECTED_PRODUCTS : 'REMOVE_SELECTED_PRODUCTS',
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    ADJUST_QUANTITY: 'ADJUST_QUANTITY',
    INCREASE_QTY:'INCREASE_QTY',
    DECREASE_QTY:'DECREASE_QTY',
    SAVE_BILLING_INFO:'SAVE_BILLING_INFO',
    CLEAR_CART: 'CLEAR_CART'
}